#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BinzelApp2_Prototipo.Resource", IsApplication=true)]

namespace BinzelApp2_Prototipo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050008
			public const int app_Lilac = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int back_White = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int black = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int dark_Lilac = 2131034122;
			
			// aapt resource value: 0x7f050004
			public const int gray = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int gray_dark = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int leaf_green = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int light_Lilac = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int red = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int sky_blue = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int white = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int yellow = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int binzel_app_icon_dark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int binzel_app_icon_light = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int binzel_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int desenho1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int sign_blue_in_process = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int sign_gray_not_started = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int sign_green_dot = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int sign_red_cancel = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int splash_screen = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000e
			public const int DtOpImg_status = 2131296270;
			
			// aapt resource value: 0x7f090008
			public const int DtOpLbl_Cliente = 2131296264;
			
			// aapt resource value: 0x7f090005
			public const int DtOpLbl_Op = 2131296261;
			
			// aapt resource value: 0x7f090013
			public const int DtOpLbl_fim = 2131296275;
			
			// aapt resource value: 0x7f090010
			public const int DtOpLbl_inicio = 2131296272;
			
			// aapt resource value: 0x7f090004
			public const int DtOpLinLay_Op = 2131296260;
			
			// aapt resource value: 0x7f090015
			public const int DtOpListView = 2131296277;
			
			// aapt resource value: 0x7f090003
			public const int DtOpRelLay_Header = 2131296259;
			
			// aapt resource value: 0x7f090009
			public const int DtOpTxt_client = 2131296265;
			
			// aapt resource value: 0x7f090014
			public const int DtOpTxt_fim = 2131296276;
			
			// aapt resource value: 0x7f090011
			public const int DtOpTxt_inicio = 2131296273;
			
			// aapt resource value: 0x7f090006
			public const int DtOpTxt_num = 2131296262;
			
			// aapt resource value: 0x7f09000a
			public const int DtOpTxt_produto = 2131296266;
			
			// aapt resource value: 0x7f09000d
			public const int DtOpTxt_status = 2131296269;
			
			// aapt resource value: 0x7f090017
			public const int RL_InnerMain = 2131296279;
			
			// aapt resource value: 0x7f090030
			public const int Text2 = 2131296304;
			
			// aapt resource value: 0x7f090033
			public const int Text3 = 2131296307;
			
			// aapt resource value: 0x7f09003b
			public const int apCel_codigo = 2131296315;
			
			// aapt resource value: 0x7f09003e
			public const int apCel_descricao = 2131296318;
			
			// aapt resource value: 0x7f090042
			public const int apCel_fim = 2131296322;
			
			// aapt resource value: 0x7f09003f
			public const int apCel_inicio = 2131296319;
			
			// aapt resource value: 0x7f090046
			public const int apCel_status = 2131296326;
			
			// aapt resource value: 0x7f09004a
			public const int apImg_Status = 2131296330;
			
			// aapt resource value: 0x7f090040
			public const int apLbl_descricao = 2131296320;
			
			// aapt resource value: 0x7f090047
			public const int apLbl_fim = 2131296327;
			
			// aapt resource value: 0x7f090043
			public const int apLbl_inicio = 2131296323;
			
			// aapt resource value: 0x7f09003d
			public const int apTxt_codigo = 2131296317;
			
			// aapt resource value: 0x7f090041
			public const int apTxt_descricao = 2131296321;
			
			// aapt resource value: 0x7f090048
			public const int apTxt_dtFim = 2131296328;
			
			// aapt resource value: 0x7f090044
			public const int apTxt_dtInicial = 2131296324;
			
			// aapt resource value: 0x7f090049
			public const int apTxt_hrFim = 2131296329;
			
			// aapt resource value: 0x7f090045
			public const int apTxt_hrInicial = 2131296325;
			
			// aapt resource value: 0x7f090021
			public const int btnEventos = 2131296289;
			
			// aapt resource value: 0x7f09001b
			public const int btnLoginOk = 2131296283;
			
			// aapt resource value: 0x7f090020
			public const int btnOrdens = 2131296288;
			
			// aapt resource value: 0x7f09001e
			public const int btnRelFunc = 2131296286;
			
			// aapt resource value: 0x7f09001d
			public const int btnRelOPs = 2131296285;
			
			// aapt resource value: 0x7f09001f
			public const int btnReports = 2131296287;
			
			// aapt resource value: 0x7f09002c
			public const int btn_Finalizar = 2131296300;
			
			// aapt resource value: 0x7f09002b
			public const int btn_Parada = 2131296299;
			
			// aapt resource value: 0x7f090031
			public const int cel_Cliente = 2131296305;
			
			// aapt resource value: 0x7f090028
			public const int cel_Fim = 2131296296;
			
			// aapt resource value: 0x7f090032
			public const int cel_Inicio = 2131296306;
			
			// aapt resource value: 0x7f09002f
			public const int cel_OP = 2131296303;
			
			// aapt resource value: 0x7f09002d
			public const int cel_Sts = 2131296301;
			
			// aapt resource value: 0x7f090039
			public const int dtFim = 2131296313;
			
			// aapt resource value: 0x7f090036
			public const int dtInicial = 2131296310;
			
			// aapt resource value: 0x7f09003a
			public const int hrFim = 2131296314;
			
			// aapt resource value: 0x7f090037
			public const int hrInicial = 2131296311;
			
			// aapt resource value: 0x7f090001
			public const int imageView1 = 2131296257;
			
			// aapt resource value: 0x7f090018
			public const int imgLogo = 2131296280;
			
			// aapt resource value: 0x7f09002e
			public const int imgStatus = 2131296302;
			
			// aapt resource value: 0x7f090038
			public const int lblFim = 2131296312;
			
			// aapt resource value: 0x7f090035
			public const int lblInicial = 2131296309;
			
			// aapt resource value: 0x7f09001c
			public const int lblMenu1Titulo = 2131296284;
			
			// aapt resource value: 0x7f090027
			public const int linLay_Tarefa = 2131296295;
			
			// aapt resource value: 0x7f090007
			public const int linearLayout1 = 2131296263;
			
			// aapt resource value: 0x7f09000b
			public const int linearLayout2 = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int linearLayout3 = 2131296268;
			
			// aapt resource value: 0x7f09000f
			public const int linearLayout4 = 2131296271;
			
			// aapt resource value: 0x7f090012
			public const int linearLayout5 = 2131296274;
			
			// aapt resource value: 0x7f090016
			public const int listView_OPs = 2131296278;
			
			// aapt resource value: 0x7f09004c
			public const int menuOptExit = 2131296332;
			
			// aapt resource value: 0x7f09004e
			public const int menuProd_Op_AddColab = 2131296334;
			
			// aapt resource value: 0x7f09004f
			public const int menuProd_Op_desenho = 2131296335;
			
			// aapt resource value: 0x7f09004d
			public const int menuProd_Op_iniciar = 2131296333;
			
			// aapt resource value: 0x7f090002
			public const int menuProd_User = 2131296258;
			
			// aapt resource value: 0x7f090024
			public const int numOP = 2131296292;
			
			// aapt resource value: 0x7f09002a
			public const int relLay_Btns = 2131296298;
			
			// aapt resource value: 0x7f090022
			public const int relativeLayout1 = 2131296290;
			
			// aapt resource value: 0x7f09003c
			public const int tarefaLbl_codigo = 2131296316;
			
			// aapt resource value: 0x7f090000
			public const int toolbar = 2131296256;
			
			// aapt resource value: 0x7f09004b
			public const int toolbarCustom = 2131296331;
			
			// aapt resource value: 0x7f090029
			public const int txtApont = 2131296297;
			
			// aapt resource value: 0x7f090025
			public const int txtCliente = 2131296293;
			
			// aapt resource value: 0x7f090019
			public const int txtName = 2131296281;
			
			// aapt resource value: 0x7f090034
			public const int txtProdDesc = 2131296308;
			
			// aapt resource value: 0x7f090026
			public const int txtProduto = 2131296294;
			
			// aapt resource value: 0x7f09001a
			public const int txtPwd = 2131296282;
			
			// aapt resource value: 0x7f090023
			public const int txtStatus = 2131296291;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Desenho = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int DetailsOP = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ListaOrdemProducao = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int MenuGerencial = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int MenuProducao = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int OPEmProducao = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int rowOP = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int rowTarefa = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int toolbar = 2130968585;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int menuGer_bar = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int menuHome_bar = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int menuProd_bar = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int menuProd_OpDetails_bar = 2131230723;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_build_white_48dp = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_camera_alt_white_48dp = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ic_close_white_24dp = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ic_menu_search_holo_dark = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ic_person_add_white_48dp = 2130903044;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06001c
			public const int action_exit = 2131099676;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060010
			public const int btn_OpDt_adicionar = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int btn_OpDt_desenho = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int btn_OpDt_iniciar = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int btn_cancel = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int btn_eventos = 2131099660;
			
			// aapt resource value: 0x7f060003
			public const int btn_login_ok = 2131099651;
			
			// aapt resource value: 0x7f06000d
			public const int btn_ok = 2131099661;
			
			// aapt resource value: 0x7f06000b
			public const int btn_ops = 2131099659;
			
			// aapt resource value: 0x7f060013
			public const int btn_rel_func = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int btn_rel_ops = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int btn_reports = 2131099668;
			
			// aapt resource value: 0x7f06001f
			public const int close_app_message = 2131099679;
			
			// aapt resource value: 0x7f06000a
			public const int detailsOP_MsgOPVazio = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int detailsOP_titulo = 2131099657;
			
			// aapt resource value: 0x7f06001e
			public const int exit_message = 2131099678;
			
			// aapt resource value: 0x7f060019
			public const int lbl_ApontCod = 2131099673;
			
			// aapt resource value: 0x7f060016
			public const int lbl_Client_list = 2131099670;
			
			// aapt resource value: 0x7f06001a
			public const int lbl_Descr = 2131099674;
			
			// aapt resource value: 0x7f060018
			public const int lbl_Fim_list = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int lbl_Ini_list = 2131099671;
			
			// aapt resource value: 0x7f060015
			public const int lbl_Op_list = 2131099669;
			
			// aapt resource value: 0x7f06001b
			public const int lbl_QtdProd = 2131099675;
			
			// aapt resource value: 0x7f060001
			public const int login_text = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int menuGer_msgAbrirOP = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int menuGer_titulo = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int menuProd_selecione = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int menuProd_titulo = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int menuProd_tituloListaOPs = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int pwd_text = 2131099650;
			
			// aapt resource value: 0x7f06001d
			public const int warning = 2131099677;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Binzel = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int Theme_Splash = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
